app:
    resource: ../src/AppBundle/Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|fr
    locale: en

admin:
    resource: ../src/AdminBundle/Controller
    type: attribute
    prefix: /{_locale}/admin
    requirements:
        _locale: en|fr

index:
    path: '/'
    controller: 'AppBundle\Controller\MainController::index'
